<?php

use Illuminate\Database\Seeder;

class WheelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB:table('wheels')->delete();

        $wheels = array(
          array(
            'model' => 'ClubSport Wheel Base V2.5',
            'description' => 'The ClubSport Wheel Base V2.5 is a careful and precise evolution of the highly successful V2. It comes with​​ more advanced electronics and a new motor for improved feeling, functionality and even higher durability.',
            'diameter' => ,
            'rotation' => 900,
            'torque' => 8,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'CSL Elite PS4',
            'description' => 'The powerful brushless servo motor combined with the single belt drive deliver impressively detailed and strong force feedback, with ultra-smooth feeling and big ball bearings for lowest friction.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => 6,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'CSL Elite',
            'description' => 'The powerful brushless servo motor in combination with the single belt dr​ive, delivers incrediblly smooth and super-fast Force Feedback effects with instant acceleration, eliminating dead spots.',
            'diameter' => ,
            'rotation' => 1080,
            'torque' => 6,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 3,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T-GT',
            'description' => 'The T-GT offers accurate sensations to virtual racers to allow them to adapt their driving and enable them to improve their performance.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-XW Racer Sparco P310 Competition Mod',
            'description' => 'TS-XW Racer Sparco P310 Competition Mod is the first milestone of the collaboration between Thrustmaster and Sparco a highly realistic wheel, designed for competition.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-PC Racer',
            'description' => 'TS-PC Racer is Thrustmaster’s ultimate racing simulator for PC racers. It faithfully reproduces the car’s response and track conditions.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TS-PC Racer 488 Challenge Edition',
            'description' => 'For the 70th anniversary of the most famous racing brand worldwide, Ferrari, Thrustmaster is proud to present the TS-PC RACER Ferrari 488 Challenge Edition racing wheel.',
            'diameter' => 12.6,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300RS',
            'description' => '1080 degree force feedback base featuring a brushless motor and detachable racing GT style wheel.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300 RS GT',
            'description' => 'This special GT Edition of the T300 RS shows a new look of the detachable GT Style wheel and T3PA pedal set.',
            'diameter' => 11,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'T300 Ferrari Integral Racing Wheel Alcantara Edition',
            'description' => 'This special edition of the T300RS includes an 8:10 scale replica of the wheel of the Ferrari 599XX EVO and a T3PA pedal set.',
            'diameter' => 11.8,
            'rotation' => 1080,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TX Racing Wheel Ferrari 458 Italia Edition',
            'description' => 'Developed in close collaboration with Microsoft, this 7:10 scale replica of the emblematic Ferrari 458 Italia wheel is fully dedicated to Xbox One, including Binder ID and Xbox One Guide button.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'TX Racing Wheel Leather Edition',
            'description' => 'TX with upgraded leather wheel and T3PA three pedal set.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => ,
            'brushless_motor' => 1,
            'resolution' => 16,
            'brand_id' => 1,
            'drive_id' => 2,
          ),
          array(
            'model' => 'G920',
            'description' => 'Steel ball bearings, stainless steel pedals and hand-stitched leather wheel grip.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => 2.2,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 2,
            'drive_id' => 1,
          ),
          array(
            'model' => 'G29',
            'description' => 'Steel ball bearings, stainless steel pedals and hand-stitched leather wheel grip.',
            'diameter' => 11,
            'rotation' => 900,
            'torque' => 2.1,
            'brushless_motor' => 0,
            'resolution' => 16,
            'brand_id' => 2,
            'drive_id' => 1,
          ),
          array(
            'model' => '',
            'description' => '',
            'diameter' => ,
            'rotation' => ,
            'torque' => ,
            'brushless_motor' => ,
            'resolution' => ,
            'brand_id' => ,
            'drive_id' => ,
          ),
        );
    }
}
